baseURL = 'https://spokey.co.uk/'
languageCode = 'en-us'
title = 'Blog'
theme = 'github-style-spokey'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "SpokeyWheeler"
  description = "A constant reminder that life was so much better before the Internet"
  github = "SpokeyWheeler"
  linkedin = "spokey"
  url = "https://spokey.co.uk"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/avatar.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/fluidicon.png"
  location = "The Lowest of the Low"
  enableGitalk = false
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "SpokeyWheeler"
    admin = "SpokeyWheeler"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/SpokeyWheeler"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "XX-123456-789"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
