baseURL = 'https://spokey.co.uk/'
languageCode = 'en-us'
title = 'Blog'
theme = 'github-style-spokey'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "SpokeyWheeler"
  description = "A constant reminder that life was so much better before the Internet"
  github = "SpokeyWheeler"
  linkedin = "spokey"
  url = "https://spokeywheeler.github.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/avatar.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/fluidicon.png"
  location = "The Lowest of the Low"
  enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

  [params.gitalk]
    clientID = "Ov23lidpCMPBPI8PHMW3"
    clientSecret = "dacda6b06beed9ee031254685b8761bd15c83aac"
    repo = "SpokeyWheeler.github.io"
    owner = "SpokeyWheeler"
    admin = "SpokeyWheeler"
    id = "location.href.match('/(?<=post/)(.*)(?=/)/')[1]"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/SpokeyWheeler"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "XX-123456-789"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = 'categories'
  tag = 'tags'
